// <auto-generated />
using System;
using FileModificationSystem.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FileModificationSystem.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20201001203353_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("FileModificationSystem.Model.Address", b =>
                {
                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("FileModificationSystem.Model.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Designation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("FileModificationSystem.Model.Qualification", b =>
                {
                    b.Property<string>("Graduation")
                        .HasColumnType("TEXT");

                    b.ToTable("Qualification");
                });
#pragma warning restore 612, 618
        }
    }
}
